apiVersion: apps/v1
kind: Deployment
metadata:
  name: balu
  namespaces: nginx 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balu
  template:
    metadata:
      name: testpod9
      labels:
        app: balu
    spec:
      containers:
      - name: balu
        image: nginx:latest
        port: 80
        targetPort: 80
