apiVersion: apps/v1
kind: Deployment
metadata:
  name: balu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balu
  template:
    metadata:
      name: testpod9
      labels:
        app: balu
    spec:
      containers:
      - name: balu
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
