apiVersion: v1
kind: Pod
metadata:
  name: initcontainer
spec:
  initContainers:
    - name: c1
      image: centos
      command: ["/bin/bash", "-c", "echo balu wadave > /tmp/xchange/testfile; sleep 30"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/xchange"
  containers:
    - name: c2
      image: centos
      command: ["/bin/bash", "-c", "while true; do cat /tmp/data/testfile; sleep 5; done"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/data"
  volumes:
    - name: xchange
      emptyDir: {}
