---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  # namespace: my-first-app  # Corrected field name
  labels:
    env: prod
    app: my-app
spec:
  containers:
  - name: web-server-container
    image: nginx
    ports:
    - name: http-port
      containerPort: 80
...