apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    env: prod
    app: my-app
  namespaces: my-first-app
spec:
  containers:
  - name: web-server-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http-port
        containerPort: 80
