apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespaces: my-first-app
  labels:
    env: prod
    app: my-app
  

spec:
  containers:
  - name: web-server-container
    image: nginx
    resources:

       ports:
          - name: http-port
            containerPort: 80
