---
apiVersion: v1
kind: Service
metadata:
  name: my-first-app   # Name of the service
spec:
    type: NodePort  
    selector:
        app: my-first-app     # Selects pods with the label "app=my-app"
     ports:
         - protocol: TCP
          port: 80            # Port on which the service listens
          targetPort: 80    # Port on the pods to which traffic is forwarded
          nodePort: 32057     # Specify the nodePort number
#   type: NodePort          # Expose service on a NodePort
... 