---
apiVersion: v1
kind: Service
metadata:
  name: nginx   # Name of the service
spec:
  selector:
    app: my-first-app     # Selects pods with the label "app=my-app"
  ports:
    - protocol: TCP
      port: 80        # Port on which the service listens
      targetPort: 8080
  type: NodePort          # Expose service on a NodePort
      nodePort: 30000         # Specify the nodePort number
...